
// SAFE, NON-ADULT, EMOTIONAL, FUN CONTENT

export const TD_TRUTH_LIST = [
  "What is your biggest fear in life?",
  "What is the one thing you regret the most?",
  "When was the last time you cried and why?",
  "What is a childhood memory you cherish the most?",
  "Who is the one person you wish you could talk to again?",
  "What is your biggest insecurity?",
  "If you could change one thing about your past, what would it be?",
  "What is the kindest thing someone has ever done for you?",
  "Do you believe in soulmates? Why or why not?",
  "What is a secret talent you have that no one knows about?",
  "What is the most embarrassing thing you've done in public?",
  "If you had one day left to live, how would you spend it?",
  "What is a habit of mine that annoys you (be honest)?",
  "What is your favorite quality about yourself?",
  "Have you ever broken a promise? What was it?",
  "What is the most expensive thing you've ever bought?",
  "What is your idea of a perfect date?",
  "What is one thing you want to achieve in the next 5 years?",
  "Have you ever kept a secret from your parents?",
  "What song makes you emotional every time you hear it?",
  "If you could trade lives with anyone for a day, who would it be?",
  "What is the funniest rumor you've heard about yourself?"
];

export const TD_DARE_LIST = [
  "Send a screenshot of your home screen wallpaper.",
  "Record a voice note singing 'Happy Birthday' to me.",
  "Type your name with your nose and send it.",
  "Send the 5th photo in your gallery (no cheating!).",
  "Change your profile picture to a funny cartoon for 5 minutes.",
  "Send a voice note whispering a secret.",
  "Write a 4-line poem about me right now.",
  "Send a selfie making a funny face.",
  "Send a screenshot of your last played song.",
  "Type a message with your eyes closed.",
  "Send a voice note imitating a celebrity.",
  "Describe me using only 3 emojis.",
  "Send a photo of what is directly in front of you.",
  "Reply to my last 3 messages with only emojis.",
  "Send a screenshot of your most used apps.",
  "Record a voice note saying a tongue twister 3 times fast.",
  "Draw a stick figure of me on paper and send a photo.",
  "Send a voice note laughing like a villain.",
  "Text me the first word that comes to your mind right now.",
  "Send a screenshot of your lock screen.",
  "Wear a hat or sunglasses for the next 5 minutes (send pic)."
];

export const TD_MYSTERY_LIST = [
  "Mystery: Describe your mood right now using a weather metaphor.",
  "Mystery: Send a voice note of your immediate surroundings.",
  "Mystery: What is the last thing you Googled? Be honest.",
  "Mystery: Dedicate a song to me right now.",
  "Mystery: Rate your day so far from 1 to 10 and explain why.",
  "Mystery: Send a photo of your hand holding an object nearby.",
  "Mystery: Tell me a joke (it doesn't have to be good).",
  "Mystery: What is the color of the shirt you are wearing?",
  "Mystery: Send a screenshot of your battery percentage.",
  "Mystery: If you were an animal, what would you be and why?",
  "Mystery: Send a voice note saying 'I am a potato'.",
  "Mystery: What is the last food you ate?",
  "Mystery: Send a close-up photo of your eye.",
  "Mystery: Recommend a movie I must watch.",
  "Mystery: What is your current battery percentage?",
  "Mystery: Send a random sticker you've never used before.",
  "Mystery: Type the first sentence of the last book you read.",
  "Mystery: Send a photo of the ceiling above you.",
  "Mystery: Make a wish right now and type 'Done'.",
  "Mystery: What is the last app you opened besides this one?",
  "Mystery: Send an emoji that represents your soul."
];

export const TD_DANGER_LIST = [
  "What is one thing you've never told anyone because you were afraid of judgment?",
  "Do you think we have a future together?",
  "What is the one thing I do that makes you feel most loved?",
  "Have you ever felt jealous of someone in my life?",
  "What is a lie you've told that you wish you hadn't?",
  "If we stopped talking today, what would you miss the most?",
  "What is your biggest fear regarding relationships?",
  "Have you ever cried over me?",
  "What is one thing you wish I would change?",
  "Do you think you are a good person? Why?",
  "What is a memory of us that you will never forget?",
  "If you could ask me one question and I had to answer honestly, what would it be?",
  "What is the most pain you've ever been in emotionally?",
  "Do you think love is enough to sustain a relationship?",
  "What is your definition of cheating?",
  "Have you ever doubted us?",
  "What is the most vulnerable you've ever felt?",
  "If you could apologize to one person from your past, who would it be?",
  "What is a dream you gave up on?",
  "When did you realize I was important to you?",
  "What is the deepest connection you've ever felt with someone?"
];
